// Generated by CoffeeScript 1.11.1
var C;

C = {
  range: function(l, r) {
    var breath;
    breath = r - l;
    return breath * Math.random() + l;
  },
  under: function(r) {
    return r * Math.random();
  },
  intUnder: function() {
    return Math.floor(C.under.apply(null, arguments));
  },
  intRange: function() {
    return Math.floor(C.range.apply(null, arguments));
  }
};

module.exports = C;
